name: manifesto_md
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.2
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  expandable: ^5.0.1
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_storage: ^13.0.3
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_custom_clippers: ^2.1.0
  flutter_image_stack: ^0.0.7
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.17
  get: ^4.6.6
  google_sign_in: ^7.2.0
  percent_indicator: ^4.2.5
  pinput: ^5.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
          weight: 900

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ''
