import 'package:manifesto_md/constants/app_images.dart';
import 'package:manifesto_md/models/searchitem_model.dart';

final List<SearchItem> searchItems = [
  SearchItem(
    image: Assets.imagesGs,
    title: 'General Symptoms',
    symptoms: [
      'Fever',
      'Fatigue',
      'Weakness',
      'Weight loss',
      'Loss of appetite',
      'Chills or shivering',
      'Night sweats',
      'Body aches',
      'Dehydration',
      'Dizziness',
      'Headache',
      'Pale skin',
      'Fainting',
      'Sleep disturbances',
      'Swelling in body',
      'Difficulty concentrating',
      'Mood changes',
    ],
  ),
  SearchItem(
    image: Assets.imagesSs,
    title: 'Skin Symptoms',
    symptoms: [
      'Redness (erythema)',
      'Rash or hives',
      'Itching (pruritus)',
      'Burning or stinging',
      'Dryness (xerosis)',
      'Scaling or flaking',
      'Peeling skin',
      'Crusting',
      'Swelling',
      'Blisters (vesicles/bullae)',
      'Ulcers or sores',
      'Bruising easily',
      'Bleeding from skin',
      'Moles or warts',
      'Pigmentation changes',
      'Thickened skin (lichenification)',
      'Oily skin',
      'Acne or pimples',
      'Cracks (fissures)',
      'Numbness or tingling',
      'Hardening (induration)',
      'Warmth or heat in skin',
      'Pus formation',
      'Stretch marks',
    ],
  ),
  SearchItem(
    image: Assets.imagesHn,
    title: 'Head & Neck',
    symptoms: [
      'Headache',
      'Dizziness or vertigo',
      'Neck pain or stiffness',
      'Sore throat',
      'Hoarseness',
      'Swollen lymph nodes',
      'Facial pain or pressure',
      'Sinus congestion',
      'Jaw pain',
      'Difficulty swallowing',
      'Ear pain',
      'Hearing loss',
      'Nasal discharge',
      'Runny or blocked nose',
      'Loss of smell or taste',
      'Mouth ulcers',
      'Toothache',
      'Facial swelling',
      'Lump in neck',
      'Throat dryness',
    ],
  ),
  SearchItem(
    image: Assets.imagesKd,
    title: 'Kidneys',
    symptoms: [
      'Lower back or flank pain',
      'Painful urination (dysuria)',
      'Blood in urine (hematuria)',
      'Foamy urine',
      'Swelling in ankles or feet',
      'Fatigue',
      'Loss of appetite',
      'Frequent urination at night (nocturia)',
      'High blood pressure',
      'Nausea or vomiting',
      'Fever with chills',
      'Cloudy urine',
      'Reduced urine output',
      'Dark or tea-colored urine',
      'Itchy skin (uremic pruritus)',
      'Metallic taste in mouth',
      'Shortness of breath (due to fluid retention)',
    ],
  ),
  SearchItem(
    image: Assets.imagesCt,
    title: 'Chest',
    symptoms: [
      'Chest pain or tightness',
      'Shortness of breath',
      'Cough (dry or productive)',
      'Palpitations',
      'Wheezing',
      'Chest heaviness or pressure',
      'Pain radiating to arm, jaw, or back',
      'Fatigue with exertion',
      'Bluish lips (cyanosis)',
      'Irregular heartbeat',
      'Swelling in chest wall',
      'Tenderness on touch',
      'Coughing up blood (hemoptysis)',
      'Rapid breathing',
      'Pain on deep breathing',
    ],
  ),
  SearchItem(
    image: Assets.imagesArms,
    title: 'Arms',
    symptoms: [
      'Pain or tenderness',
      'Swelling or inflammation',
      'Numbness or tingling',
      'Weakness or heaviness',
      'Rash or redness',
      'Joint stiffness',
      'Muscle cramps',
      'Bruising',
      'Limited range of motion',
      'Discoloration',
      'Coldness in hand or fingers',
      'Loss of sensation',
      'Burning pain',
      'Tremors or twitching',
    ],
  ),
  SearchItem(
    image: Assets.imagesAb,
    title: 'Abdomen',
    symptoms: [
      'Abdominal pain',
      'Bloating or fullness',
      'Nausea or vomiting',
      'Constipation',
      'Diarrhea',
      'Loss of appetite',
      'Heartburn or acid reflux',
      'Tenderness to touch',
      'Abdominal swelling',
      'Lump or mass in abdomen',
      'Gas or burping',
      'Blood in stool',
      'Cramps',
      'Yellowing of skin (jaundice)',
      'Change in bowel habits',
    ],
  ),
  SearchItem(
    image: Assets.imagesPl,
    title: 'Pelvis',
    symptoms: [
      'Pelvic pain or pressure',
      'Pain during urination',
      'Lower abdominal pain',
      'Irregular menstruation',
      'Pain during intercourse',
      'Lower back pain',
      'Frequent urination',
      'Vaginal or penile discharge',
      'Burning sensation',
      'Swelling in groin',
      'Pain radiating to thighs',
      'Fever with pelvic pain',
      'Difficulty urinating',
    ],
  ),
  SearchItem(
    image: Assets.imagesBk,
    title: 'Back',
    symptoms: [
      'Lower back pain',
      'Stiffness or limited motion',
      'Muscle spasms',
      'Pain radiating to legs',
      'Numbness or tingling',
      'Weakness',
      'Sharp or dull ache',
      'Back swelling',
      'Pain with movement',
      'Posture imbalance',
      'Difficulty standing upright',
      'Pain worse at night',
    ],
  ),
  SearchItem(
    image: Assets.imagesLg,
    title: 'Lungs',
    symptoms: [
      'Cough (persistent or with mucus)',
      'Shortness of breath',
      'Chest tightness',
      'Wheezing',
      'Coughing up blood (hemoptysis)',
      'Fatigue',
      'Chest pain on breathing',
      'Bluish skin (cyanosis)',
      'Rapid breathing',
      'Fever with cough',
      'Night sweats',
      'Weight loss (in chronic lung diseases)',
    ],
  ),
  SearchItem(
    image: Assets.imagesLeg,
    title: 'Legs',
    symptoms: [
      'Leg pain or cramps',
      'Swelling (edema)',
      'Numbness or tingling',
      'Weakness',
      'Varicose veins',
      'Coldness in feet',
      'Skin discoloration',
      'Ulcers or sores',
      'Joint stiffness',
      'Muscle fatigue',
      'Restless legs',
      'Burning sensation',
      'Difficulty walking',
      'Bruising',
    ],
  ),
];
